hotbar:
  - !<navigatorItem>
    type: COMPASS
    name: hotbar.navigator.item.name
    description: hotbar.navigator.item.description
    hotbarSlot: 0
    commandOnClick: menu

  - !<profileItem>
    type: PLAYER_HEAD
    name: hotbar.profile.item.name
    description: hotbar.profile.item.description
    hotbarSlot: 1
    commandOnClick: profile

  - !<inventoryItem>
    type: CHEST
    name: hotbar.inventory.item.name
    description: hotbar.inventory.item.description
    hotbarSlot: 4
    commandOnClick: inventory

  - !<visibilityItem>
    type: LIME_DYE
    name: hotbar.visibility.item.name
    description: hotbar.visibility.item.description
    hotbarSlot: 7
    commandOnClick: visibility

  - !<eventItem>
    type: CLOCK
    name: hotbar.event.item.name
    description: hotbar.event.item.description
    hotbarSlot: 8
    commandOnClick: event

visibilityCommand:
  item:
    slot: 7
    materialOn: LIME_DYE
    materialOff: GRAY_DYE
    enabled: true

gamesGUI:
  dataProvider:
    apiSharedMemory: true
  games:
    - !<rtf>
      gameType: rtf
      icon:
        type: RED_WOOL
        name: RushTheFlag
        description: games.menu.icon.rtf.description
        menuSlot: 20
      onClickGame:
        # Var args: <gameID> - it is defined by amount of the game icon
        #           <player> - it is defined by the player name
        runCommand: rtf spectate <gameID>

    - !<survival>
      gameType: survival
      icon:
        type: GRASS_BLOCK
        name: Survival
        description: games.menu.icon.survival.description
        menuSlot: 21
      onClickGame:
        # Var args: <gameID> - it is defined by amount of the game icon
        #           <player> - it is defined by the player name
        runCommand: survival join