hotbar:
  - !<navigatorItem>
    type: COMPASS
    name: hotbar.navigator.item.name
    description: hotbar.navigator.item.description
    hotbarSlot: 0
    commandOnClick: menu

  - !<profileItem>
    type: PLAYER_HEAD
    applySkinHeadOfPlayer: true
    name: hotbar.profile.item.name
    description: hotbar.profile.item.description
    hotbarSlot: 1
    commandOnClick: profile

  - !<shopItem>
    type: ENDER_CHEST
    name: hotbar.shop.item.name
    description: hotbar.shop.item.description
    hotbarSlot: 4
    commandOnClick: shop

  - !<visibilityItem>
    type: LIME_DYE
    name: hotbar.visibility.item.name
    description: hotbar.visibility.item.description
    hotbarSlot: 7
    commandOnClick: visibility

  - !<eventItem>
    type: CLOCK
    name: hotbar.event.item.name
    description: hotbar.event.item.description
    hotbarSlot: 8
    commandOnClick: event

visibilityCommand:
  item:
    slot: 7
    materialOn: LIME_DYE
    materialOff: GRAY_DYE
    enabled: true

# games
gamesGUI:
  dataProvider:
    apiSharedMemory: true
  games:
    - !<rtf>
      gameType: rtf
      icon:
        type: RED_WOOL
        name: RushTheFlag
        description: games.menu.icon.rtf.description
        menuSlot: 20
      joinCommand: rtf spectate <gameID>
      createCommand: rtf create <gameID>
      deleteCommand: rtf end <gameID>
      games: 3

    - !<rush>
      gameType: rush
      icon:
        type: RED_BED
        name: Rush
        description: games.menu.icon.rush.description
        menuSlot: 21
      joinCommand: rush spectate <gameID>
      createCommand: rush create <gameID>
      deleteCommand: rush end <gameID>

    - !<survival>
      gameType: survival
      icon:
        type: GRASS_BLOCK
        name: Survival
        description: games.menu.icon.survival.description
        menuSlot: 23
      joinCommand: survival spectate <gameID>
      createCommand: survival create <gameID>
      deleteCommand: survival end <gameID>

    - !<practice>
      gameType: practice
      icon:
        type: IRON_SWORD
        name: Practice
        description: games.menu.icon.practice.description
        menuSlot: 24
      joinCommand: practice spectate <gameID>
      createCommand: practice create <gameID>
      deleteCommand: practice end <gameID>

    - !<blockparty>
      gameType: blockparty
      icon:
        type: MUSIC_DISC_CAT
        name: Blockparty
        description: games.menu.icon.blockparty.description
        menuSlot: 30
      joinCommand: blockparty spectate <gameID>
      createCommand: blockparty create <gameID>
      deleteCommand: blockparty end <gameID>

    - !<laboratory>
      gameType: laboratory
      icon:
        type: BREWING_STAND
        name: Laboratory
        description: games.menu.icon.laboratory.description
        menuSlot: 31
      joinCommand: laboratory spectate <gameID>
      createCommand: laboratory create <gameID>
      deleteCommand: laboratory end <gameID>

    - !<nexus>
      gameType: nexus
      icon:
        type: NETHER_STAR
        name: Nexus
        description: games.menu.icon.nexus.description
        menuSlot: 32
      joinCommand: nexus spectate <gameID>
      createCommand: nexus create <gameID>
      deleteCommand: nexus end <gameID>

    - !<openbuild>
      gameType: openbuild
      icon:
        type: CRAFTING_TABLE
        name: Openbuild
        description: games.menu.icon.openbuild.description
        menuSlot: 40
      joinCommand: openbuild spectate <gameID>
      createCommand: openbuild create <gameID>
      deleteCommand: openbuild end <gameID>