hotbar:
  navigatorItem:
     type: COMPASS
     name: hotbar.navigator.item.name
     description: hotbar.navigator.item.description
     hotbarSlot: 4
gamesGUI:
  dataProvider:
    apiSharedMemory: true
  games:
    - !<rtf>
      gameType: rtf
      icon:
        type: RED_WOOL
        name: RushTheFlag
        description: games.menu.icon.rtf.description
        menuSlot: 20
      onClickGame:
        # Var args: <gameID> - it is defined by amount of the game icon
        #           <player> - it is defined by the player name
        runCommand: rtf spectate <gameID>